name: Super-Linter

on:
  push:

jobs:
  super-lint:
    name: Lint code base
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: docker://github/super-linter:v3
        with:
          default_branch: main
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
