name: Super-Linter

on:
  push:

jobs:
  super-lint:
    name: Lint code base
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEFAULT_BRANCH: main
